(()=>{
  const D=window.GAMING_DATA||{games:[],news:[]};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const favKey='level-ar-favorites-v4';
  let fav=JSON.parse(localStorage.getItem(favKey)||'[]');
  let newsFilter='all', gameLimit=40;
  const palette={rockstar:'#a93b32',playstation:'#185dcc',ea:'#8b4bbd',ubisoft:'#ef7d20',capcom:'#c7362f',xbox:'#248c3b',bandai:'#315da8',remedy:'#5d42a6',indie:'#087f76',blizzard:'#4b73bb',nintendo:'#d91d2b',bethesda:'#7b8d3c',square:'#3d68b4',sega:'#1967c8',konami:'#cf2c3a',epic:'#20242c',WB:'#4d2d6e',Valve:'#2c7a45',Riot:'#d72e3e',Krafton:'#1771a5',NetEase:'#d14a34',Microsoft:'#0078d4',CDPR:'#b22a2a',Larian:'#8b5a2b',Amazon:'#e47911',Embark:'#e83b30'};
  const freeGames=new Set(['Fortnite','Apex Legends','Valorant','Rocket League','Warframe','The Finals','PUBG: Battlegrounds','Overwatch 2','Call of Duty: Warzone','League of Legends','Genshin Impact','Honkai: Star Rail','Destiny 2','Fall Guys']);
  function save(){localStorage.setItem(favKey,JSON.stringify(fav));$('#favCount').textContent=fav.length}
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function companyKey(c=''){const x=c.toLowerCase(); if(x.includes('rockstar'))return'rockstar';if(x.includes('playstation'))return'playstation';if(x.includes('xbox'))return'xbox';if(x.includes('nintendo'))return'nintendo';if(x.includes('electronic arts')||x==='ea')return'ea';if(x.includes('ubisoft'))return'ubisoft';if(x.includes('capcom'))return'capcom';if(x.includes('bethesda'))return'bethesda';if(x.includes('bandai'))return'bandai';if(x.includes('remedy'))return'remedy';return 'indie'}
  function art(title,accent,kind=''){const c=palette[companyKey(accent)]||palette[accent]||'#4a5568';return `<div class="${kind}Art" style="background:radial-gradient(circle at 70% 25%,${c}88,transparent 38%),linear-gradient(135deg,${c},#0a0c10)"><div class="artTitle">${esc(title)}</div><div class="artMeta">${esc(accent)} • LEVEL AR</div></div>`}
  function isFav(id){return fav.includes(id)}
  function toggleFav(id){fav=isFav(id)?fav.filter(x=>x!==id):[...fav,id];save();renderAll();toast(isFav(id)?'تمت الإضافة للمفضلة':'تمت الإزالة من المفضلة')}
  function newsCard(n){return `<article class="newsCard"><div class="newsArt" style="background:radial-gradient(circle at 70% 20%,${palette[companyKey(n.company)]||'#555'}99,transparent 38%),linear-gradient(135deg,${palette[companyKey(n.company)]||'#555'},#0a0c10)"><div class="artTitle">${esc(n.game)}</div><div class="artMeta">${esc(n.type)} • ${esc(n.date)}</div></div><div class="newsBody"><span class="tag">${n.official?'رسمي':'غير مؤكد'}</span><h3>${esc(n.title)}</h3><p>المصدر: ${esc(n.source)} — يمكنك فتح المصدر الأصلي للتحقق من التفاصيل.</p><div class="cardFoot"><span class="source">${esc(n.source)} • ${esc(n.date)}</span><div class="miniActions"><button data-news="${esc(n.id)}">قراءة</button><button data-fav="${esc(n.id)}" aria-label="مفضلة">${isFav(n.id)?'♥':'♡'}</button></div></div></div></article>`}
  function renderNews(){let arr=D.news.filter(n=>newsFilter==='all'||companyKey(n.company)===newsFilter);arr=[...arr].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#newsGrid').innerHTML=arr.length?arr.map(newsCard).join(''):'<div class="emptyState">لا توجد أخبار مؤكدة من هذا المصدر في قاعدة البيانات الحالية. جرّب «الكل» أو مصدرًا آخر.</div>'}
  function gamePrice(g){return g.price|| (freeGames.has(g.title)?'مجاني':'حسب المتجر والمنصة')}
  function gameRating(g){return g.rating||'غير مضاف بعد'}
  function gameCard(g){return `<article class="gameCard" data-game="${esc(g.id)}">${art(g.title,g.company,'game')}<div class="gameInfo"><h3>${esc(g.title)}</h3><p>${esc(g.company)} • ${esc(g.platforms)}</p><div class="gameMeta"><span>💰 ${esc(gamePrice(g))}</span><span>⭐ ${esc(gameRating(g))}</span></div></div></article>`}
  function renderGames(){let q=($('#gameSearch')?.value||'').trim().toLowerCase(),company=$('#companyFilter')?.value||'all',platform=$('#platformFilter')?.value||'all';let arr=D.games.filter(g=>(company==='all'||g.company===company)&& (platform==='all'||g.platforms.toLowerCase().includes(platform.toLowerCase())) && (!q||g.title.toLowerCase().includes(q)||g.studio.toLowerCase().includes(q)||g.company.toLowerCase().includes(q)));$('#gamesGrid').innerHTML=arr.slice(0,gameLimit).map(gameCard).join('');$('#loadMore').style.display=arr.length>gameLimit?'block':'none';$('#gamesCount').textContent=`${arr.length} لعبة`}
  function renderFav(){let items=[];D.games.forEach(g=>{if(isFav(g.id))items.push(gameCard(g))});D.news.forEach(n=>{if(isFav(n.id))items.push(newsCard(n))});$('#favoritesGrid').innerHTML=items.length?items.join(''):'<div class="emptyState">لم تحفظ أي لعبة أو خبر بعد.</div>'}
  function renderAll(){renderNews();renderGames();renderFav()}
  function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
  function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');$('#modalContent').innerHTML=''}
  function openNews(id){let n=D.news.find(x=>x.id===id);if(!n)return;modal(`<div class="modalArt" style="background:radial-gradient(circle at 70% 25%,${palette[companyKey(n.company)]||'#555'}99,transparent 40%),linear-gradient(135deg,${palette[companyKey(n.company)]||'#555'},#0a0c10)"><h2>${esc(n.game)}</h2></div><span class="tag">${esc(n.type)}</span><h2>${esc(n.title)}</h2><p class="modalMeta">${esc(n.source)} • ${esc(n.date)} • ${n.official?'مصدر رسمي':'غير مؤكد'}</p><p>هذا ملخص عربي قصير. التفاصيل الكاملة موجودة في المصدر الأصلي.</p><div class="modalActions"><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">المصدر الأصلي ↗</a><button data-fav="${esc(n.id)}">${isFav(n.id)?'إزالة من المفضلة':'إضافة للمفضلة'}</button><button data-share="${esc(n.id)}">مشاركة</button></div>`)}
  function openGame(id){let g=D.games.find(x=>x.id===id);if(!g)return;let related=D.news.filter(n=>n.game.toLowerCase().includes(g.title.toLowerCase())||g.title.toLowerCase().includes(n.game.toLowerCase())).slice(0,5);modal(`${art(g.title,g.company,'modal')}<h2>${esc(g.title)}</h2><div class="detailGrid"><div><b>المطور</b><span>${esc(g.studio)}</span></div><div><b>الشركة</b><span>${esc(g.company)}</span></div><div><b>المنصات</b><span>${esc(g.platforms)}</span></div><div><b>السعر</b><span>${esc(gamePrice(g))}</span></div><div><b>التقييم</b><span>⭐ ${esc(gameRating(g))}</span></div><div><b>الحالة</b><span>${g.releaseDate?esc(g.releaseDate):'معلومات الإصدار حسب المصدر'}</span></div></div><div class="modalActions"><button data-fav="${esc(g.id)}">${isFav(g.id)?'إزالة من المفضلة':'حفظ اللعبة'}</button><button data-check="${esc(g.id)}">هل جهازي يشغلها؟</button></div><hr><h3>آخر الأخبار المرتبطة</h3>${related.length?related.map(n=>`<p>• ${esc(n.title)}</p>`).join(''):'<p>لا توجد أخبار مرتبطة حاليًا.</p>'}<p class="muted">ملاحظة: الأسعار والتقييمات تتغير حسب المتجر والمنطقة، لذلك لن نعرض رقمًا مخترعًا. عند إضافة مصدر موثوق سيظهر الرقم هنا.</p>`)}
  function checker(){modal(`<h2>هل جهازك يشغل اللعبة؟</h2><p class="modalMeta">أدخل مواصفات جهازك للمقارنة. النتيجة إرشادية وليست ضمانًا لمعدل الإطارات.</p><div class="checker"><input id="cpu" placeholder="المعالج CPU"><input id="gpu" placeholder="كرت الشاشة GPU"><input id="ram" type="number" placeholder="RAM GB"><select id="level"><option>أريد 1080p</option><option>أريد 1440p</option><option>أريد 4K</option></select></div><button class="wideBtn" id="runCheck">فحص</button><div id="checkResult"></div>`)}
  function videos(){const vids=[['GTA VI — Trailer 1','QdBZY2fkU-0','Rockstar Games'],['GTA VI — Trailer 2','VQRLujxTm3c','Rockstar Games'],['GTA VI — An Extended Look','YmzCydc4qOk','Rockstar Games']];$('#videoGrid').innerHTML=vids.map(v=>`<article class="videoCard"><div class="videoFrame"><iframe src="https://www.youtube-nocookie.com/embed/${v[1]}" title="${esc(v[0])}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="videoInfo"><h3>${esc(v[0])}</h3><p>${esc(v[2])} • مشغل YouTube الرسمي.</p></div></article>`).join('')}
  function releases(){const list=[['15 سبتمبر 2026','Marvel’s Wolverine','PS5'],['17 سبتمبر 2026','Fire Emblem: Fortune’s Weave','Nintendo Switch 2'],['18 سبتمبر 2026','LEGO Batman: Legacy of the Dark Knight','Nintendo Switch 2'],['24 سبتمبر 2026','Control Resonant','PC / PS5 / Xbox Series X|S'],['25 سبتمبر 2026','EA SPORTS FC 27','PC / PS5 / PS4 / Xbox / Switch'],['2 أكتوبر 2026','Ace Combat 8: Wings of Theve','PS5 / Xbox / PC'],['19 نوفمبر 2026','Grand Theft Auto VI','PS5 / Xbox Series X|S'],['4 فبراير 2027','Muramasa: Revenant Blades','PS5']];$('#releaseGrid').innerHTML=list.map(x=>`<article class="release"><div class="date">${esc(x[0])}</div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('')}
  function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
  function share(id){let n=D.news.find(x=>x.id===id),url=location.href.split('#')[0]+'#news-'+id;if(n&&navigator.share)navigator.share({title:n.title,text:'من LEVEL AR',url});else{navigator.clipboard?.writeText(url);toast('تم نسخ رابط الخبر')}}
  $('#newsFilters').addEventListener('click',e=>{let b=e.target.closest('[data-filter]');if(!b)return;$$('#newsFilters .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');newsFilter=b.dataset.filter;renderNews()});
  $('#gameSearch').addEventListener('input',()=>{gameLimit=40;renderGames()});
  $('#companyFilter').innerHTML='<option value="all">كل الشركات</option>'+[...new Set(D.games.map(g=>g.company))].sort().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
  $('#platformFilter').addEventListener('change',()=>{gameLimit=40;renderGames()});
  $('#companyFilter').addEventListener('change',()=>{gameLimit=40;renderGames()});
  $('#loadMore').addEventListener('click',()=>{gameLimit+=40;renderGames()});
  $$('.platform').forEach(p=>p.addEventListener('click',e=>{e.preventDefault();let v=p.dataset.platform;$('#platformFilter').value=v;$('#companyFilter').value='all';gameLimit=40;renderGames();location.hash='#games';setTimeout(()=>$('#games').scrollIntoView({behavior:'smooth'}),0)}));
  $('#searchBtn').onclick=()=>{location.hash='#games';setTimeout(()=>$('#gameSearch').focus(),50)};
  document.addEventListener('click',e=>{let n=e.target.closest('[data-news]'),g=e.target.closest('[data-game]'),f=e.target.closest('[data-fav]'),s=e.target.closest('[data-share]'),c=e.target.closest('[data-check]');if(n){openNews(n.dataset.news);return}if(g){openGame(g.dataset.game);return}if(f){toggleFav(f.dataset.fav);return}if(s){share(s.dataset.share);return}if(c){checker();return}let act=e.target.closest('[data-action]')?.dataset.action;if(act==='checker')checker();if(act==='favorites')location.hash='#favorites';if(act==='all-news'){newsFilter='all';$$('#newsFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderNews();location.hash='#news'}if(act==='popular')toast('سيتم ترتيب الترند تلقائيًا مع بيانات التفاعل');if(act==='compare')toast('المقارنة الأساسية جاهزة ويمكن تطويرها لاحقًا')});
  $('#modalClose').onclick=closeModal;$('.modalBackdrop').onclick=closeModal;$('#menuBtn').onclick=()=>$('.nav').classList.toggle('open');$('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});window.addEventListener('scroll',()=>$('#topBtn').classList.toggle('show',scrollY>500));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
  $('#ticker').textContent=D.news.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8).map(n=>n.title).join('  •  ');
  videos();releases();save();renderAll();setTimeout(()=>$('#loading').style.display='none',450);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
