(()=>{
  'use strict';
  const D=window.GAMING_DATA||{games:[],news:[]};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const favKey='level-ar-favorites-v5', viewsKey='level-ar-views-v5';
  let fav=[], views={}, newsFilter='all', gameLimit=40;
  try{fav=JSON.parse(localStorage.getItem(favKey)||'[]');}catch{}
  try{views=JSON.parse(localStorage.getItem(viewsKey)||'{}');}catch{}
  const palette={rockstar:'#a93b32',playstation:'#185dcc',ea:'#8b4bbd',ubisoft:'#ef7d20',capcom:'#c7362f',xbox:'#248c3b',bandai:'#315da8',remedy:'#5d42a6',indie:'#087f76',blizzard:'#4b73bb',nintendo:'#d91d2b',bethesda:'#7b8d3c',square:'#3d68b4',sega:'#1967c8',konami:'#cf2c3a',epic:'#20242c',wb:'#4d2d6e',valve:'#2c7a45',riot:'#d72e3e',krafton:'#1771a5',netease:'#d14a34',microsoft:'#0078d4',cdpr:'#b22a2a',larian:'#8b5a2b',amazon:'#e47911',embark:'#e83b30',activision:'#555'};
  const freeGames=new Set(['Fortnite','Apex Legends','Valorant','Rocket League','Warframe','The Finals','PUBG: Battlegrounds','Overwatch 2','Call of Duty: Warzone','League of Legends','Genshin Impact','Honkai: Star Rail','Destiny 2','Fall Guys']);
  const companyAliases={
    'rockstar':'rockstar','rockstar games':'rockstar','rockstar games / playstation':'rockstar','playstation':'playstation','xbox':'xbox','nintendo':'nintendo','ea':'ea','electronic arts':'ea','ubisoft':'ubisoft','capcom':'capcom','bethesda':'bethesda','bandai':'bandai','bandai namco':'bandai','remedy':'remedy','remedy entertainment':'remedy','blizzard':'blizzard','activision':'activision','cdpr':'cdpr','cd projekt red':'cdpr','square':'square','sega':'sega','epic':'epic','wb':'wb','valve':'valve','riot':'riot','krafton':'krafton','netease':'netease','microsoft':'microsoft','amazon':'amazon','embark':'embark','indie':'indie'
  };
  const companyKey=c=>companyAliases[String(c||'').trim().toLowerCase()]||String(c||'indie').trim().toLowerCase();
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalizePlatform=p=>{const x=String(p||'').toLowerCase(); if(x.includes('playstation')||x.includes('ps5'))return'PS5';if(x.includes('ps4'))return'PS4';if(x.includes('xbox'))return'Xbox';if(x.includes('switch'))return'Switch';if(x.includes('mobile')||x.includes('android')||x.includes('iphone')||x.includes('ios'))return'Mobile';if(x.includes('pc')||x.includes('steam')||x.includes('epic'))return'PC';return'other'};
  function save(){localStorage.setItem(favKey,JSON.stringify(fav));localStorage.setItem(viewsKey,JSON.stringify(views));const c=$('#favCount');if(c)c.textContent=fav.length;}
  function isFav(id){return fav.includes(id)}
  function toggleFav(id){const had=isFav(id);fav=had?fav.filter(x=>x!==id):[...fav,id];save();renderAll();toast(had?'تمت الإزالة من المفضلة':'تمت الإضافة للمفضلة');}
  function bump(id){views[id]=(views[id]||0)+1;save();}
  function priceText(g){if(g.price&&g.price!=='حسب المتجر والمنصة')return g.price;return freeGames.has(g.title)?'مجاني':'يختلف حسب المتجر والمنصة'}
  function ratingText(g){return g.rating&&g.rating!=='غير مضاف بعد'?g.rating:'غير متوفر حاليًا'}
  function storeLinks(g){const q=encodeURIComponent(g.title);const p=String(g.platforms||'').toLowerCase();const a=[];if(p.includes('pc'))a.push(`<a href="https://store.steampowered.com/search/?term=${q}" target="_blank" rel="noopener">Steam</a>`);if(p.includes('ps'))a.push(`<a href="https://store.playstation.com/en-us/search/${q}" target="_blank" rel="noopener">PlayStation Store</a>`);if(p.includes('xbox'))a.push(`<a href="https://www.xbox.com/en-us/search?q=${q}" target="_blank" rel="noopener">Xbox Store</a>`);if(p.includes('switch'))a.push(`<a href="https://www.nintendo.com/us/search/#q=${q}" target="_blank" rel="noopener">Nintendo</a>`);if(!a.length)a.push(`<a href="https://www.google.com/search?q=${q}+official+store" target="_blank" rel="noopener">البحث عن المتجر الرسمي</a>`);return a.join(' • ')}
  function art(title,company,kind=''){const c=palette[companyKey(company)]||'#4a5568';return `<div class="${kind}Art" style="background:radial-gradient(circle at 70% 25%,${c}88,transparent 38%),linear-gradient(135deg,${c},#0a0c10)"><div class="artTitle">${esc(title)}</div><div class="artMeta">${esc(company)} • LEVEL AR</div></div>`}
  function newsCard(n){return `<article class="newsCard"><div class="newsArt" style="background:radial-gradient(circle at 70% 20%,${palette[companyKey(n.company)]||'#555'}99,transparent 38%),linear-gradient(135deg,${palette[companyKey(n.company)]||'#555'},#0a0c10)"><div class="artTitle">${esc(n.game)}</div><div class="artMeta">${esc(n.type)} • ${esc(n.date)}</div></div><div class="newsBody"><span class="tag">${n.official?'رسمي':'غير مؤكد'}</span><h3>${esc(n.title)}</h3><p>${esc(n.source)} • ${esc(n.date)}</p><div class="cardFoot"><span class="source">${esc(n.company)}</span><div class="miniActions"><button data-news="${esc(n.id)}">فتح الخبر</button><button data-fav="${esc(n.id)}" aria-label="مفضلة">${isFav(n.id)?'♥':'♡'}</button></div></div></div></article>`}
  function renderNews(){const q=($('#newsSearch')?.value||'').trim().toLowerCase();let arr=D.news.filter(n=>(newsFilter==='all'||companyKey(n.company)===newsFilter)&&(!q||`${n.title} ${n.game} ${n.source} ${n.company}`.toLowerCase().includes(q)));arr.sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#newsGrid').innerHTML=arr.length?arr.map(newsCard).join(''):'<div class="emptyState">لا توجد نتائج لهذا الفلتر. اختر «الكل» أو شركة أخرى.</div>'}
  function gameCard(g){return `<article class="gameCard" data-game="${esc(g.id)}">${art(g.title,g.company,'game')}<div class="gameInfo"><h3>${esc(g.title)}</h3><p>${esc(g.company)} • ${esc(g.platforms)}</p><div class="gameMeta"><span>💰 ${esc(priceText(g))}</span><span>⭐ ${esc(ratingText(g))}</span></div><div class="gameStoreHint">عرض السعر والمتجر ↗</div></div></article>`}
  function renderGames(){const q=($('#gameSearch')?.value||'').trim().toLowerCase(),company=$('#companyFilter')?.value||'all',platform=$('#platformFilter')?.value||'all';let arr=D.games.filter(g=>(company==='all'||g.company===company)&&(platform==='all'||normalizePlatform(g.platforms)===platform||String(g.platforms).toLowerCase().includes(platform.toLowerCase()))&&(!q||`${g.title} ${g.studio} ${g.company}`.toLowerCase().includes(q)));$('#gamesGrid').innerHTML=arr.slice(0,gameLimit).map(gameCard).join('');$('#gamesEmpty').hidden=arr.length>0;$('#loadMore').style.display=arr.length>gameLimit?'block':'none';$('#gamesCount').textContent=`${arr.length} لعبة`}
  function renderFav(){const items=[];D.games.forEach(g=>{if(isFav(g.id))items.push(gameCard(g))});D.news.forEach(n=>{if(isFav(n.id))items.push(newsCard(n))});$('#favoritesGrid').innerHTML=items.length?items.join(''):'<div class="emptyState">لم تحفظ أي لعبة أو خبر بعد.</div>'}
  function renderAll(){renderNews();renderGames();renderFav()}
  function buildNewsFilters(){const root=$('#newsFilters');const companies=[...new Set(D.news.map(n=>companyKey(n.company)))].filter(Boolean);const labels={rockstar:'Rockstar',playstation:'PlayStation',xbox:'Xbox',nintendo:'Nintendo',ea:'EA',ubisoft:'Ubisoft',capcom:'Capcom',bethesda:'Bethesda',bandai:'Bandai Namco',remedy:'Remedy'};root.innerHTML='<button class="chip active" data-filter="all">الكل</button>'+companies.map(k=>`<button class="chip" data-filter="${esc(k)}">${esc(labels[k]||k)}</button>`).join('')}
  function buildCompanyFilter(){const root=$('#companyFilter');const companies=[...new Set(D.games.map(g=>g.company))].sort((a,b)=>a.localeCompare(b));root.innerHTML='<option value="all">كل الشركات</option>'+companies.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}
  function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
  function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');$('#modalContent').innerHTML=''}
  function openNews(id){const n=D.news.find(x=>x.id===id);if(!n)return;bump(id);modal(`<div class="modalArt" style="background:radial-gradient(circle at 70% 25%,${palette[companyKey(n.company)]||'#555'}99,transparent 40%),linear-gradient(135deg,${palette[companyKey(n.company)]||'#555'},#0a0c10)"><h2>${esc(n.game)}</h2></div><span class="tag">${esc(n.type)}</span><h2>${esc(n.title)}</h2><p class="modalMeta">${esc(n.source)} • ${esc(n.date)} • ${n.official?'مصدر رسمي':'غير مؤكد'}</p><p>هذا الخبر مرتبط بالمصدر الأصلي. افتح المصدر لقراءة التفاصيل الكاملة والتحقق من آخر تحديث.</p><div class="modalActions"><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">المصدر الأصلي ↗</a><button data-fav="${esc(n.id)}">${isFav(n.id)?'إزالة من المفضلة':'إضافة للمفضلة'}</button><button data-share="${esc(n.id)}">مشاركة</button></div>`)}
  function openGame(id){const g=D.games.find(x=>x.id===id);if(!g)return;bump(id);const related=D.news.filter(n=>n.game.toLowerCase().includes(g.title.toLowerCase())||g.title.toLowerCase().includes(n.game.toLowerCase())||companyKey(n.company)===companyKey(g.company)).slice(0,5);modal(`${art(g.title,g.company,'modal')}<h2>${esc(g.title)}</h2><div class="detailGrid"><div><b>المطور</b><span>${esc(g.studio)}</span></div><div><b>الشركة</b><span>${esc(g.company)}</span></div><div><b>المنصات</b><span>${esc(g.platforms)}</span></div><div><b>السعر</b><span>${esc(priceText(g))}</span></div><div><b>التقييم</b><span>⭐ ${esc(ratingText(g))}</span></div><div><b>الإصدار</b><span>${g.releaseDate?esc(g.releaseDate):'غير مضاف حاليًا'}</span></div></div><div class="storeBox"><b>الأسعار والمتاجر الرسمية</b><div>${storeLinks(g)}</div></div><div class="modalActions"><button data-fav="${esc(g.id)}">${isFav(g.id)?'إزالة من المفضلة':'حفظ اللعبة'}</button><button data-check="${esc(g.id)}">هل جهازي يشغلها؟</button></div><hr><h3>آخر الأخبار المرتبطة</h3>${related.length?related.map(n=>`<p>• <a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a></p>`).join(''):'<p>لا توجد أخبار مرتبطة بهذه اللعبة حاليًا.</p>'}<p class="muted">الأسعار والتقييمات تختلف حسب المتجر والمنطقة؛ LEVEL AR لا يخترع رقمًا غير موثق.</p>`)}
  function checker(){modal(`<h2>هل جهازك يشغل اللعبة؟</h2><p class="modalMeta">أدخل مواصفات جهازك للمقارنة. النتيجة إرشادية وليست ضمانًا لمعدل الإطارات.</p><div class="checker"><input id="cpu" placeholder="المعالج CPU"><input id="gpu" placeholder="كرت الشاشة GPU"><input id="ram" type="number" placeholder="RAM GB"><select id="level"><option>1080p</option><option>1440p</option><option>4K</option></select></div><button class="wideBtn" id="runCheck">فحص</button><div id="checkResult"></div>`)}
  function runChecker(){const r=Number($('#ram')?.value||0),result=$('#checkResult');if(!r){result.innerHTML='<p class="emptyState">اكتب حجم الرام أولًا.</p>';return}result.innerHTML=`<div class="checkResult"><b>نتيجة مبدئية</b><p>${r>=16?'الرام مناسبة لمعظم الألعاب الحديثة.':'يفضل 16GB RAM للألعاب الحديثة.'}</p><small>لنتيجة أدق نحتاج مقارنة المعالج وكرت الشاشة بمتطلبات اللعبة نفسها.</small></div>`}
  function videos(){const vids=[['GTA VI — Trailer 1','QdBZY2fkU-0','Rockstar Games'],['GTA VI — Trailer 2','VQRLujxTm3c','Rockstar Games'],['GTA VI — An Extended Look','YmzCydc4qOk','Rockstar Games'],['Marvel’s Wolverine — Gameplay Deep Dive','oQO2zf8YQNI','PlayStation']];$('#videoGrid').innerHTML=vids.map(v=>`<article class="videoCard"><a class="videoThumb" href="https://www.youtube.com/watch?v=${v[1]}" target="_blank" rel="noopener"><img src="https://i.ytimg.com/vi/${v[1]}/hqdefault.jpg" alt="${esc(v[0])}" loading="lazy"><span>▶</span></a><div class="videoInfo"><h3>${esc(v[0])}</h3><p>${esc(v[2])} • مشاهدة على YouTube</p></div></article>`).join('')}
  function releases(){const list=[['15 سبتمبر 2026','Marvel’s Wolverine','PS5'],['17 سبتمبر 2026','Fire Emblem: Fortune’s Weave','Nintendo Switch 2'],['18 سبتمبر 2026','LEGO Batman: Legacy of the Dark Knight','Nintendo Switch 2'],['24 سبتمبر 2026','Control Resonant','PC / PS5 / Xbox Series X|S'],['25 سبتمبر 2026','EA SPORTS FC 27','PC / PlayStation / Xbox / Switch'],['2 أكتوبر 2026','Ace Combat 8','PS5 / Xbox / PC'],['19 نوفمبر 2026','Grand Theft Auto VI','PS5 / Xbox Series X|S']];$('#releaseGrid').innerHTML=list.map(x=>`<article class="release"><div class="date">${esc(x[0])}</div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('')}
  function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
  async function share(id){const n=D.news.find(x=>x.id===id),url=location.href.split('#')[0]+'#news-'+id;if(n&&navigator.share){try{await navigator.share({title:n.title,text:'من LEVEL AR',url})}catch{}}else{try{await navigator.clipboard.writeText(url);toast('تم نسخ رابط الخبر')}catch{toast('تعذر نسخ الرابط')}}}
  function applyPlatform(v){$('#platformFilter').value=v;$('#companyFilter').value='all';gameLimit=40;renderGames();location.hash='#games';setTimeout(()=>$('#games').scrollIntoView({behavior:'smooth'}),0)}
  $('#newsFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;$$('#newsFilters .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');newsFilter=b.dataset.filter;renderNews()});
  $('#newsSearch').addEventListener('input',renderNews);$('#gameSearch').addEventListener('input',()=>{gameLimit=40;renderGames()});$('#platformFilter').addEventListener('change',()=>{gameLimit=40;renderGames()});$('#companyFilter').addEventListener('change',()=>{gameLimit=40;renderGames()});$('#loadMore').addEventListener('click',()=>{gameLimit+=40;renderGames()});
  $$('.platform').forEach(p=>p.addEventListener('click',e=>{e.preventDefault();applyPlatform(p.dataset.platform)}));
  $('#searchBtn').onclick=()=>{location.hash='#games';setTimeout(()=>$('#gameSearch').focus(),50)};
  document.addEventListener('click',e=>{const n=e.target.closest('[data-news]'),g=e.target.closest('[data-game]'),f=e.target.closest('[data-fav]'),s=e.target.closest('[data-share]'),c=e.target.closest('[data-check]'),run=e.target.closest('#runCheck');if(n){openNews(n.dataset.news);return}if(g){openGame(g.dataset.game);return}if(f){toggleFav(f.dataset.fav);return}if(s){share(s.dataset.share);return}if(c){checker();return}if(run){runChecker();return}const act=e.target.closest('[data-action]')?.dataset.action;if(act==='checker')checker();if(act==='favorites')location.hash='#favorites';if(act==='all-news'){newsFilter='all';$$('#newsFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderNews();location.hash='#news'}if(act==='popular'){const top=[...D.games].sort((a,b)=>(views[b.id]||0)-(views[a.id]||0)).slice(0,10);$('#gameSearch').value='';$('#companyFilter').value='all';$('#platformFilter').value='all';gameLimit=10;$('#gamesGrid').innerHTML=top.map(gameCard).join('');location.hash='#games';setTimeout(()=>$('#games').scrollIntoView({behavior:'smooth'}),0)}if(act==='compare')toast('اختار لعبة من القائمة لعرض تفاصيلها ومقارنتها لاحقًا')});
  $('#modalClose').onclick=closeModal;$('.modalBackdrop').onclick=closeModal;$('#menuBtn').onclick=()=>$('.nav').classList.toggle('open');$('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'});window.addEventListener('scroll',()=>$('#topBtn').classList.toggle('show',scrollY>500));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
  buildNewsFilters();buildCompanyFilter();$('#ticker').textContent=D.news.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8).map(n=>n.title).join(' • ');videos();releases();save();renderAll();
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js?v=5').then(r=>r.update()).catch(()=>{});setTimeout(()=>$('#loading').style.display='none',350);
})();
